const ROPROST_WORKER_URL='https://roprost-live-api.oscarinfantemoran.workers.dev';
function rpLiveNorm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,'').trim()}
function rpLiveKey(a,b){return rpLiveNorm(a)+'|'+rpLiveNorm(b)}
function rpVal(v){if(v===null||v===undefined)return 0;if(typeof v==='string')return Number(v.replace('%',''))||0;return Number(v)||0}
async function rpFetchWorkerLive(){try{let r=await fetch(ROPROST_WORKER_URL+'/live?t='+Date.now());let data=await r.json();return (data.response||[]).map(x=>{let st=x.fixture?.status||{},home=x.teams?.home?.name||'',away=x.teams?.away?.name||'',stats=x.statistics||[];function stat(team,type){let row=stats.find(s=>rpLiveNorm(s.team?.name)===rpLiveNorm(team));let val=(row?.statistics||[]).find(a=>String(a.type).toLowerCase()===String(type).toLowerCase())?.value;return rpVal(val)}return{key:rpLiveKey(home,away),local:home,visita:away,homeScore:rpVal(x.goals?.home),awayScore:rpVal(x.goals?.away),score:rpVal(x.goals?.home)+'-'+rpVal(x.goals?.away),minute:st.elapsed?st.elapsed+"'":(st.short||'Pendiente'),state:st.short||'',completed:st.short==='FT'||st.long==='Match Finished',corners:stat(home,'Corner Kicks')+stat(away,'Corner Kicks'),cards:stat(home,'Yellow Cards')+stat(away,'Yellow Cards')+stat(home,'Red Cards')+stat(away,'Red Cards'),shots:stat(home,'Total Shots')+stat(away,'Total Shots'),shotsOn:stat(home,'Shots on Goal')+stat(away,'Shots on Goal'),posHome:stat(home,'Ball Possession'),posAway:stat(away,'Ball Possession'),source:'API-Football'}})}catch(e){return[]}}
async function rpFetchEspnLive(){let out=[];try{let r=await fetch('https://site.api.espn.com/apis/site/v2/sports/soccer/all/scoreboard?limit=500&t='+Date.now());let data=await r.json();(data.events||[]).forEach(ev=>{let c=ev.competitions&&ev.competitions[0];if(!c||!c.competitors||c.competitors.length<2)return;let h=c.competitors.find(x=>x.homeAway==='home')||c.competitors[0],a=c.competitors.find(x=>x.homeAway==='away')||c.competitors[1],st=c.status&&c.status.type?c.status.type:{};out.push({key:rpLiveKey(h.team.displayName||h.team.name,a.team.displayName||a.team.name),local:h.team.displayName||h.team.name,visita:a.team.displayName||a.team.name,homeScore:Number(h.score||0),awayScore:Number(a.score||0),score:(h.score||0)+'-'+(a.score||0),minute:st.shortDetail||st.detail||'Pendiente',state:st.state||'',completed:!!st.completed,corners:0,cards:0,shots:0,shotsOn:0,posHome:0,posAway:0,source:'ESPN'})})}catch(e){}return out}
async function rpFetchLiveMatches(){let api=await rpFetchWorkerLive();if(api.length)return api;return await rpFetchEspnLive()}
function rpLiveEval(m,live){let txt=String(m||'').toLowerCase(),g=live.homeScore+live.awayScore;if(txt.includes('corner')){if(!live.corners)return null;if(txt.includes('mas de'))return live.corners>parseFloat(txt.match(/mas de ([0-9.]+)/)?.[1]||0);if(txt.includes('menos de'))return live.corners<parseFloat(txt.match(/menos de ([0-9.]+)/)?.[1]||99)}if(txt.includes('tarjeta')){if(!live.cards)return null;if(txt.includes('mas de'))return live.cards>parseFloat(txt.match(/mas de ([0-9.]+)/)?.[1]||0);if(txt.includes('menos de'))return live.cards<parseFloat(txt.match(/menos de ([0-9.]+)/)?.[1]||99)}if(txt.includes('mas de')&&txt.includes('goles'))return g>parseFloat(txt.match(/mas de ([0-9.]+)/)?.[1]||0);if(txt.includes('menos de')&&txt.includes('goles'))return g<parseFloat(txt.match(/menos de ([0-9.]+)/)?.[1]||99);if(txt.includes('ambos anotan: si'))return live.homeScore>0&&live.awayScore>0;if(txt.includes('ambos anotan: no'))return live.homeScore===0||live.awayScore===0;return null}
function rpFindLiveForItem(item,live){let k=rpLiveKey(item.local,item.visita);return live.find(x=>x.key===k)||live.find(x=>rpLiveNorm(x.local).includes(rpLiveNorm(item.local))&&rpLiveNorm(x.visita).includes(rpLiveNorm(item.visita)))}
function rpRenderLiveGroupedRows(items,prefix,live){return rpGroupByMatch(items).reverse().map((g,i)=>{let id=prefix+'-'+i,one=g.items[0],lv=rpFindLiveForItem(one,live),extra=lv&&lv.source==='API-Football'?`<br>🚩 Córners ${lv.corners} · 🟨 Tarjetas ${lv.cards} · 🎯 Tiros ${lv.shotsOn}/${lv.shots}`:'',liveBox=lv?`<small>🔴 ${lv.source} · ${lv.minute} · Marcador ${lv.score}${extra}</small>`:`<small>Esperando datos en vivo</small>`;let details=g.items.map(x=>{let st=rpStatusLabel(x),lv2=rpFindLiveForItem(x,live),ok=lv2?rpLiveEval(x.mercado,lv2):null,cls=ok===true?'pill-ok':(ok===false&&lv2?.completed?'pill-risk':st[2]),label=ok===true?'CUMPLIDO':(ok===false&&lv2?.completed?'PERDIDA':st[1]),emoji=ok===true?'✅':(ok===false&&lv2?.completed?'❌':st[0]),res=lv2?`${lv2.score} · Córners ${lv2.corners||'s/d'} · Tarjetas ${lv2.cards||'s/d'}`:(x.resultado||'pendiente');return `<div class="pick rp-detail-row"><b>${emoji} ${x.mercado}<br><small>${x.prob}% · ${res}${lv2?' · '+lv2.minute:''}</small></b><span class="${cls}">${label}</span></div>`}).join('');let completed=g.items.filter(x=>{let lv3=rpFindLiveForItem(x,live);return lv3&&rpLiveEval(x.mercado,lv3)===true}).length;let pill=completed?['✅',completed+' cumplidos','pill-ok']:rpGroupStatus(g.items);return `<div class="pick rp-match-row" onclick="rpToggleGroup('${id}')"><b>${pill[0]} ${g.local} vs ${g.visita}<br>${liveBox}<small>${g.items.length} pronóstico(s) guardado(s)</small></b><span class="${pill[2]}">${pill[1]}</span></div><div id="${id}" class="rp-detail-box" style="display:none">${details}</div>`}).join('')}
async function rpUpdateLiveResults(){if(typeof rpGetSavedPicks!=='function')return;let saved=rpGetSavedPicks(),live=await rpFetchLiveMatches();let box=document.getElementById('rp-results-list');if(!box)return;if(!saved.length){box.innerHTML='<div class="empty">Aún no hay pronósticos guardados.</div>';return}let liveCount=saved.filter(x=>rpFindLiveForItem(x,live)).length;box.innerHTML=`<p class="info rp-summary"><b>Resumen</b><span>🔴 ${liveCount}</span><span>📊 Live</span><span>30s</span></p>`+rpRenderLiveGroupedRows(saved,'rp-live-now',live)}
(function(){window.addEventListener('load',function(){setTimeout(rpUpdateLiveResults,2500);setInterval(rpUpdateLiveResults,30000);let old=window.rpUpdateResults;window.rpUpdateResults=async function(){if(typeof old==='function')await old();setTimeout(rpUpdateLiveResults,500)}})})();
